### ISSUE TITLE
Is there a way to visualize structure matrix?

### ISSUE THREAD

**Issue by wzm2256** [omrysendik/DCor#1]
Is there a way to visualize structure matrix as in fig2?

**Comment by omrysendik** [comment]
Hi,

Thanks for asking!
Simply call ACorrTensor = CalcACorrTensor(Feats) which returns the deep autocorr tensor and then choose which index of the maps to plot by imshow(ACorrTensor(:,:,ChosenInd),[]);
Let me know if this suffices.

**Comment by wzm2256** [comment]
@omrysendik Well, when the size is even number, like (128,128,1), it doesn't work, since the size does not fit when use dot divide . I resize it to (129, 129, 1) and it works well.

**Comment by omrysendik** [comment]
That's right.
This released version doesn't support even sizes images.
Notice that there's an assertion in Verify.m.
